
-- SELECT building, count(*) FROM places where building is not null group by building;
-- SELECT landuse, count(*) FROM places where landuse is not null group by landuse;

-- SELECT NAME, tags from places where ((NAME IS NULL OR NAME = '') AND (TAGS IS NULL OR TAGS = ''))

-- SELECT highway, count(*) FROM planet_osm_point where highway is not null group by highway ;

-- delete from places where highway != 'bus_stop' and highway is not null;
-- select highway, count(*) from places where highway != 'bus_stop' and highway is not null group by highway;
-- select "generator:source", count(*) from places where "generator:source" is not null group by "generator:source";
-- select * from places;
-- select highway, name, tags from places where highway = 'platform';
-- delete from places where railway is not null;
-- delete from places where power is not null;
-- delete from places where barrier is not null;



-- delete from places where ((NAME IS NULL OR NAME = '') AND (TAGS IS NULL OR TAGS = ''))

-- select * from planet_osm_polygon where water is not null --NOT (NAME IS NULL OR NAME = '') 

-- INSERT INTO PLACES ("osm_id",
-- "access",
-- "addr:housename",
-- "addr:housenumber",
-- "addr:interpolation",
-- "admin_level",
-- "aerialway",
-- "aeroway",
-- "amenity",
-- "area",
-- "barrier",
-- "bicycle",
-- "brand",
-- "bridge",
-- "boundary",
-- "building",
-- "construction",
-- "covered",
-- "culvert",
-- "cutting",
-- "denomination",
-- "disused",
-- "embankment",
-- "foot",
-- "generator:source",
-- "harbour",
-- "highway",
-- "historic",
-- "horse",
-- "intermittent",
-- "junction",
-- "landuse",
-- "layer",
-- "leisure",
-- "lock",
-- "man_made",
-- "military",
-- "motorcar",
-- "name",
-- "natural",
-- "office",
-- "oneway",
-- "operator",
-- "place",
-- "population",
-- "power",
-- "power_source",
-- "public_transport",
-- "railway",
-- "ref",
-- "religion",
-- "route",
-- "service",
-- "shop",
-- "sport",
-- "surface",
-- "toll",
-- "tourism",
-- "tower:type",
-- "tunnel",
-- "water",
-- "waterway",
-- "wetland",
-- "width",
-- "wood",
-- "z_order",
-- "tags",
-- "way")
-- SELECT "osm_id",
-- "access",
-- "addr:housename",
-- "addr:housenumber",
-- "addr:interpolation",
-- "admin_level",
-- "aerialway",
-- "aeroway",
-- "amenity",
-- "area",
-- "barrier",
-- "bicycle",
-- "brand",
-- "bridge",
-- "boundary",
-- "building",
-- "construction",
-- "covered",
-- "culvert",
-- "cutting",
-- "denomination",
-- "disused",
-- "embankment",
-- "foot",
-- "generator:source",
-- "harbour",
-- "highway",
-- "historic",
-- "horse",
-- "intermittent",
-- "junction",
-- "landuse",
-- "layer",
-- "leisure",
-- "lock",
-- "man_made",
-- "military",
-- "motorcar",
-- "name",
-- "natural",
-- "office",
-- "oneway",
-- "operator",
-- "place",
-- "population",
-- "power",
-- "power_source",
-- "public_transport",
-- "railway",
-- "ref",
-- "religion",
-- "route",
-- "service",
-- "shop",
-- "sport",
-- "surface",
-- "toll",
-- "tourism",
-- "tower:type",
-- "tunnel",
-- "water",
-- "waterway",
-- "wetland",
-- "width",
-- "wood",
-- "z_order",
-- "tags",
-- ST_PointN(ST_Exteriorring("way"), 1) FROM PLANET_OSM_POLYGON;

-- select * from places where osm_id = '623905355'

delete from places where concat(
"aerialway",
"aeroway",
"amenity",
"area",
"barrier",
"bicycle",
"brand",
"bridge",
"boundary",
"building",
"construction",
"covered",
"culvert",
"cutting",
"denomination",
"disused",
"embankment",
"foot",
"generator:source",
"harbour",
"highway",
"historic",
"horse",
"intermittent",
"junction",
"landuse",
"layer",
"leisure",
"lock",
"man_made",
"military",
"motorcar",
"natural",
"office",
"oneway",
"operator",
"place",
"population",
"power",
"power_source",
"public_transport",
"railway",
"ref",
"religion",
"route",
"service",
"shop",
"sport",
"surface",
"toll",
"tourism",
"tower:type",
"tunnel",
"water",
"waterway",
"wetland",
"width",
"wood") = '';