EXPLAIN ANALYZE VERBOSE
SELECT AMENITY,
			NAME,
			SHOP,
			SPORT,
			PUBLIC_TRANSPORT,
			TAGS,
			WATER,
			LANDUSE
		FROM PLANET_OSM_POLYGON
		WHERE HIGHWAY IS NULL
			AND RAILWAY IS NULL
			AND POWER IS NULL
			AND BARRIER IS NULL
			AND (BUILDING != 'garage'
								AND BUILDING != 'apartments'
								OR BUILDING IS NULL)
			AND (LANDUSE != 'grass'
								OR LANDUSE IS NULL)
			AND (SHOP IS NOT NULL
								OR LEISURE IS NOT NULL
								OR PUBLIC_TRANSPORT IS NOT NULL
			         			OR AMENITY IS NOT NULL
								OR WATER IS NOT NULL)
			AND NOT ((NAME IS NULL OR NAME = '') AND (TAGS IS NULL OR TAGS = ''))
			AND (0 = 0 OR ST_DWITHIN(WAY, ST_TRANSFORM(ST_SETSRID(ST_POINT(20.97954, 52.25052), 4326), 3857), 0) = false)
			AND ST_DWITHIN(WAY, ST_TRANSFORM(ST_SETSRID(ST_POINT(20.97954, 52.25052), 4326), 3857), 500);