locationTypes:
  - tobacco
  - massage
  - agrarian
  - hearing_aids
  - pet_grooming
  - fabric
  - department_store
  - perfumery
  - tattoo
  - seafood
  - photo
  - locksmith
  - motorcycle
  - art
  - bookmaker
  - paint
  - gift
  - houseware
  - tyres
  - lottery
  - medical_supply
  - e-cigarette
  - interior_decoration
  - laundry
  - confectionery
  - dry_cleaning
  - boutique
  - wholesale
  - deli
  - pawnbroker
  - wine
  - trade
  - tailor
  - ticket
  - travel_agency
  - stationery
  - funeral_directors
  - toys
  - garden_centre
  - cosmetics
  - computer
  - sports
  - hardware
  - newsagent
  - variety_store
  - copyshop
  - car_parts
  - vacant
  - pet
  - pastry
  - bicycle
  - mobile_phone
  - jewelry
  - doityourself
  - electronics
  - mall
  - books
  - greengrocer
  - shoes
  - furniture
  - yes
  - car
  - optician
  - alcohol
  - butcher
  - kiosk
  - chemist
  - florist
  - car_repair
  - beauty
  - bakery
  - hairdresser
  - clothes
  - supermarket
  - convenience
  - training
  - hunting_stand
  - food_court
  - studio
  - compressed_air
  - clock
  - trolley_bay
  - lounger
  - public_building
  - enclosing
  - cinema
  - car_rental
  - courthouse
  - bus_station
  - nightclub
  - childcare
  - events_venue
  - theatre
  - taxi
  - language_school
  - driving_school
  - bicycle_repair_station
  - hospital
  - bureau_de_change
  - college
  - drinking_water
  - university
  - marketplace
  - arts_centre
  - pub
  - charging_station
  - vehicle_inspection
  - post_box
  - fountain
  - police
  - veterinary
  - community_centre
  - ice_cream
  - townhall
  - bar
  - social_facility
  - clinic
  - library
  - bicycle_rental
  - toilets
  - post_office
  - car_wash
  - dentist
  - recycling
  - cafe
  - doctors
  - fire_station
  - bank
  - fuel
  - waste_disposal
  - atm
  - kindergarten
  - fast_food
  - pharmacy
  - school
  - place_of_worship
  - parcel_locker
  - parking_entrance
  - restaurant
  - shelter
  - vending_machine
  - waste_basket
  - bicycle_parking
  - bench
  - parking_space
  - parking
  - stream
  - wastewater
  - lake
  - oxbow
  - river
  - basin
  - reservoir
  - pond
  - chess
  - equestrian
  - swimming
  - skateboard
  - handball
  - beachvolleyball
  - table_tennis
  - volleyball
  - running
  - fitness
  - athletics
  - multi
  - tennis
  - basketball
  - soccer
