locationTypes:
    - accounting_office
    - agriculture
    - animal_training
    - anime
    - antiques
    - art_supplies
    - arts
    - auction
    - auction_house
    - baby_care
    - baby_hatch
    - baggage_lockers
    - balloons_with_helium
    - basin
    - beauty_salon
    - beauty_supply
    - binoculars
    - boat_storage
    - brewery
    - brush
    - bulletproof_glass
    - camera
    - candles
    - canteen
    - car;car_parts
    - car_pooling
    - car_sharing
    - chair
    - charity
    - chemists
    - coffee;tea
    - collector
    - community
    - compressed_air
    - computer_repair
    - concert_hall
    - construction_machines
    - construction_materials
    - cooking_school
    - cosmetic_surgeon
    - country_store
    - coworking_space
    - crypt
    - customs
    - dancing_school
    - delivery_depot
    - dental_care
    - dentures
    - diet
    - dive_centre
    - dog_toilet
    - dog_wash
    - dormitory
    - dressing_room
    - driver_training
    - e_scooter
    - electric
    - employment_agency
    - enclosing
    - energy
    - engraver
    - erotic
    - events_centre
    - factory
    - fashion_accessories
    - fast_foos
    - feeding_place
    - ferry_terminal
    - financial_advice
    - fire_protection
    - fishing;weapons
    - fixme
    - flag
    - flares
    - flats
    - flooring
    - foils
    - frame
    - freeshop
    - frozen_food
    - funeral_home
    - furnace
    - garden_design
    - garden_furniture
    - geodesy
    - give_box
    - government
    - groundskeeping
    - haberdashery
    - healthcare
    - hearing_aids
    - heating_systems
    - herbs
    - hifi
    - honey
    - household_linen
    - hunting
    - hunting_stand
    - internet_cafe
    - juice_bar
    - kancelaria
    - keys
    - knife
    - knitting
    - laundry_box
    - lawyer
    - letter_box
    - library_dropoff
    - loading_dock
    - lost_and_found
    - lounger
    - machinery
    - mangle
    - mattress
    - military_surplus
    - mill
    - ministry
    - miscallenous
    - miscellaneous
    - model
    - money_lender
    - motorbike
    - movie_studio
    - musical_instrument
    - nails
    - newspapers
    - notary
    - numismatics
    - nutrition_supplements
    - office_supplies
    - outdoor;hunting
    - outpost
    - parcel_pickup
    - payment_terminal
    - pest_control
    - photo;bookmaker
    - photo_booth
    - place_of_mourning
    - planetarium
    - planned
    - pole
    - post_box
    - pottery
    - power_supply
    - presbytery
    - pressing
    - printer_ink
    - printing
    - proposed
    - public_bath
    - public_bookcase
    - publisher
    - pyrotechnics
    - recording_studio
    - reef_aquarium
    - regional
    - register_office
    - rental
    - repair
    - rescue_station
    - restaurant
    - retail
    - robot
    - safe
    - safety_equipment
    - sailing_school
    - sanitary
    - scooter
    - scooter_parking
    - scout
    - scuba_diving
    - second_hand
    - security
    - services
    - shisha
    - shop_housing_estate
    - ski
    - skład_budowlany
    - spices
    - spy
    - stage
    - statistics
    - stock_exchange
    - stone
    - stripclub
    - sunbed
    - supplements
    - swimming_pool
    - table
    - telecommunication
    - translations
    - trolley_bay
    - various
    - vending_machine
    - video
    - video_games
    - warehouse
    - washing_machine
    - waste_basket
    - watch_repair
    - watchmaker
    - wigs
    - window_construction
    - wine; cheese
    - wine_bar
